"""add task version field for optimistic concurrency

Revision ID: 195d74ed876f
Revises: 98c5f85cf29e
Create Date: 2026-02-09 17:01:32.608386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195d74ed876f'
down_revision: Union[str, Sequence[str], None] = '98c5f85cf29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add version column with server_default for existing rows
    op.add_column('task', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    # Remove server_default after column is populated
    op.alter_column('task', 'version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'version')
    # ### end Alembic commands ###
