"""add_auth_fields_to_user

Revision ID: 98c5f85cf29e
Revises: 
Create Date: 2026-01-12 18:17:10.589697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c5f85cf29e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds authentication fields to User table. For existing users:
    - password_hash: Set to empty string (users must reset password)
    - status: Set to 'ACTIVE' (all existing users remain active)
    - password_changed_at: Set to NULL (no password change yet)
    """
    # Create UserStatus enum type
    userstatus_enum = sa.Enum('ACTIVE', 'DISABLED', 'DELETED', name='userstatus')
    userstatus_enum.create(op.get_bind(), checkfirst=True)

    # Add columns as NULLABLE first to allow existing rows
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('user', sa.Column('status', userstatus_enum, nullable=True))
    op.add_column('user', sa.Column('password_changed_at', sa.DateTime(), nullable=True))

    # Set default values for existing users
    op.execute("UPDATE \"user\" SET password_hash = '' WHERE password_hash IS NULL")
    op.execute("UPDATE \"user\" SET status = 'ACTIVE' WHERE status IS NULL")

    # Now make password_hash and status NOT NULL
    op.alter_column('user', 'password_hash', nullable=False)
    op.alter_column('user', 'status', nullable=False)

    # Create index on status
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Removes authentication fields from User table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_column('user', 'password_changed_at')
    op.drop_column('user', 'status')
    op.drop_column('user', 'password_hash')

    # Drop UserStatus enum type
    userstatus_enum = sa.Enum('ACTIVE', 'DISABLED', 'DELETED', name='userstatus')
    userstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
